/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Modelo.ZonaTrabajo;
import java.util.ArrayList;

/**
 *
 * @author Hernan
 */
public class InterfazGit extends javax.swing.JFrame {
    
    private ZonaTrabajo Zona;
    
    /**
     * Creates new form InterfazGit
     */
    public InterfazGit() {
        initComponents();
        this.setLocationRelativeTo(null);
        jPanelMenuAdd.setVisible(false);
        jPanelMenuAdd2.setVisible(false);
        jPanelMenuAdd2.setVisible(false);
        jPanelMenuInit.setVisible(false);
        jPanelMenuNewArchivo.setVisible(false);
        jPanelStatus.setVisible(false);
        jPanelMenuCommit.setVisible(false);   
        jPanelVentanaInformacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanelMenuCommit = new javax.swing.JPanel();
        jFieldAutorCommit = new javax.swing.JTextField();
        jFieldMensajeCommit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnAceptarCommit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanelMenuAdd2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFieldNombreAdd2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnAceptarAdd2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStatusWorkspaceAdd = new javax.swing.JTextArea();
        jPanelMenuAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnAgregarTodosAdd = new javax.swing.JButton();
        jbtnSeleccionarAdd = new javax.swing.JButton();
        jPanelMenuInit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAceptInit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jFieldAutorInit = new javax.swing.JTextField();
        jFieldNombreInit = new javax.swing.JTextField();
        jPanelMenuNewArchivo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnAceptarNewArchivo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jFieldNombreNewArchivo = new javax.swing.JTextField();
        jFieldContenidoNewArchivo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanelStatus = new javax.swing.JPanel();
        jFieldTituloPanelStatus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAreaInformacion = new javax.swing.JTextArea();
        jbtnAceptarPanelStatus = new javax.swing.JButton();
        jPanelVentanaInformacion = new javax.swing.JPanel();
        jFieldInformacionVInformacion = new javax.swing.JTextField();
        jbtnAceptarInformacion = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnStaWork = new javax.swing.JButton();
        btnStaInd = new javax.swing.JButton();
        btnStaLoc = new javax.swing.JButton();
        btnStaRem = new javax.swing.JButton();
        btnInit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCommit = new javax.swing.JButton();
        btnNewArchivo = new javax.swing.JButton();
        btnPull = new javax.swing.JButton();
        btnPush = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnZonaTrabajo = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(526, 460));
        setMinimumSize(new java.awt.Dimension(526, 460));
        setPreferredSize(new java.awt.Dimension(526, 460));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenuCommit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jFieldAutorCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldAutorCommitActionPerformed(evt);
            }
        });

        jFieldMensajeCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldMensajeCommitActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingrese Autor Commit:");

        jLabel7.setText("Ingrese Mensaje Descriptivo:");

        jbtnAceptarCommit.setText("Aceptar");
        jbtnAceptarCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarCommitActionPerformed(evt);
            }
        });

        jLabel8.setText("Menu Commit");

        javax.swing.GroupLayout jPanelMenuCommitLayout = new javax.swing.GroupLayout(jPanelMenuCommit);
        jPanelMenuCommit.setLayout(jPanelMenuCommitLayout);
        jPanelMenuCommitLayout.setHorizontalGroup(
            jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCommitLayout.createSequentialGroup()
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuCommitLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFieldAutorCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldMensajeCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMenuCommitLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel8))
                    .addGroup(jPanelMenuCommitLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jbtnAceptarCommit)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelMenuCommitLayout.setVerticalGroup(
            jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCommitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFieldAutorCommit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFieldMensajeCommit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnAceptarCommit)
                .addContainerGap())
        );

        getContentPane().add(jPanelMenuCommit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 340, 160));

        jPanelMenuAdd2.setMaximumSize(new java.awt.Dimension(528, 493));
        jPanelMenuAdd2.setMinimumSize(new java.awt.Dimension(528, 493));
        jPanelMenuAdd2.setPreferredSize(new java.awt.Dimension(528, 493));

        jLabel4.setText("Ingrese Nombres de Archivos: ");

        jFieldNombreAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNombreAdd2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Menu Add");

        jbtnAceptarAdd2.setText("Aceptar");
        jbtnAceptarAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarAdd2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Formato de Ingreso: NombreArchivo NombreArchivo NombreArchivo");

        jLabel3.setText("Workspace");

        jTextAreaStatusWorkspaceAdd.setEditable(false);
        jTextAreaStatusWorkspaceAdd.setColumns(20);
        jTextAreaStatusWorkspaceAdd.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaStatusWorkspaceAdd.setRows(5);
        jScrollPane1.setViewportView(jTextAreaStatusWorkspaceAdd);

        javax.swing.GroupLayout jPanelMenuAdd2Layout = new javax.swing.GroupLayout(jPanelMenuAdd2);
        jPanelMenuAdd2.setLayout(jPanelMenuAdd2Layout);
        jPanelMenuAdd2Layout.setHorizontalGroup(
            jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuAdd2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addGap(119, 119, 119))
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFieldNombreAdd2)
                        .addContainerGap())))
            .addGroup(jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(404, 404, 404))
                .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                    .addGap(219, 219, 219)
                    .addComponent(jbtnAceptarAdd2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                .addGroup(jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel5))
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMenuAdd2Layout.setVerticalGroup(
            jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFieldNombreAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAceptarAdd2)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanelMenuAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 430));

        jLabel1.setText("Menu Add");

        jbtnAgregarTodosAdd.setText("Agregar todos los archivos");
        jbtnAgregarTodosAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarTodosAddActionPerformed(evt);
            }
        });

        jbtnSeleccionarAdd.setText("Selecionar archivos a agregar");
        jbtnSeleccionarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuAddLayout = new javax.swing.GroupLayout(jPanelMenuAdd);
        jPanelMenuAdd.setLayout(jPanelMenuAddLayout);
        jPanelMenuAddLayout.setHorizontalGroup(
            jPanelMenuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAddLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1))
            .addGroup(jPanelMenuAddLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jbtnAgregarTodosAdd))
            .addGroup(jPanelMenuAddLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jbtnSeleccionarAdd))
        );
        jPanelMenuAddLayout.setVerticalGroup(
            jPanelMenuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAddLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jbtnAgregarTodosAdd)
                .addGap(5, 5, 5)
                .addComponent(jbtnSeleccionarAdd))
        );

        getContentPane().add(jPanelMenuAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 90));

        jPanelMenuInit.setPreferredSize(new java.awt.Dimension(360, 180));

        jLabel9.setText("Ingrese Nombre Autor:");

        jLabel10.setText("Ingrese Nombre Repositorio:");

        btnAceptInit.setText("Aceptar");
        btnAceptInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptInitActionPerformed(evt);
            }
        });

        jLabel11.setText("Menu Init");

        jFieldAutorInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldAutorInitActionPerformed(evt);
            }
        });

        jFieldNombreInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNombreInitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuInitLayout = new javax.swing.GroupLayout(jPanelMenuInit);
        jPanelMenuInit.setLayout(jPanelMenuInitLayout);
        jPanelMenuInitLayout.setHorizontalGroup(
            jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuInitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptInit)
                .addGap(133, 133, 133))
            .addGroup(jPanelMenuInitLayout.createSequentialGroup()
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuInitLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFieldAutorInit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFieldNombreInit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMenuInitLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel11)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelMenuInitLayout.setVerticalGroup(
            jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuInitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(16, 16, 16)
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jFieldAutorInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jFieldNombreInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptInit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenuInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 360, 180));

        jLabel12.setText("Ingrese Contenido Archivo:");

        btnAceptarNewArchivo.setText("Aceptar");
        btnAceptarNewArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarNewArchivoActionPerformed(evt);
            }
        });

        jLabel13.setText("Menu Nuevo Archivo");

        jFieldNombreNewArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldNombreNewArchivoActionPerformed(evt);
            }
        });

        jFieldContenidoNewArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldContenidoNewArchivoActionPerformed(evt);
            }
        });

        jLabel14.setText("Ingrese Nombre Archivo:");

        javax.swing.GroupLayout jPanelMenuNewArchivoLayout = new javax.swing.GroupLayout(jPanelMenuNewArchivo);
        jPanelMenuNewArchivo.setLayout(jPanelMenuNewArchivoLayout);
        jPanelMenuNewArchivoLayout.setHorizontalGroup(
            jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuNewArchivoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFieldNombreNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldContenidoNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuNewArchivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(118, 118, 118))
            .addGroup(jPanelMenuNewArchivoLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btnAceptarNewArchivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuNewArchivoLayout.setVerticalGroup(
            jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuNewArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFieldNombreNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jFieldContenidoNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptarNewArchivo)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenuNewArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 340, 160));

        jAreaInformacion.setColumns(20);
        jAreaInformacion.setRows(5);
        jScrollPane2.setViewportView(jAreaInformacion);

        jbtnAceptarPanelStatus.setText("Aceptar");

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFieldTituloPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnAceptarPanelStatus)
                .addGap(189, 189, 189))
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFieldTituloPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAceptarPanelStatus)
                .addContainerGap())
        );

        getContentPane().add(jPanelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 230, 140));

        jPanelVentanaInformacion.setMaximumSize(new java.awt.Dimension(360, 121));
        jPanelVentanaInformacion.setMinimumSize(new java.awt.Dimension(360, 121));

        jbtnAceptarInformacion.setText("Aceptar");
        jbtnAceptarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarInformacionActionPerformed(evt);
            }
        });

        jLabel15.setText("Informacion");

        javax.swing.GroupLayout jPanelVentanaInformacionLayout = new javax.swing.GroupLayout(jPanelVentanaInformacion);
        jPanelVentanaInformacion.setLayout(jPanelVentanaInformacionLayout);
        jPanelVentanaInformacionLayout.setHorizontalGroup(
            jPanelVentanaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                .addGroup(jPanelVentanaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jFieldInformacionVInformacion))
                    .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jbtnAceptarInformacion)
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaInformacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(145, 145, 145))
        );
        jPanelVentanaInformacionLayout.setVerticalGroup(
            jPanelVentanaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(24, 24, 24)
                .addComponent(jFieldInformacionVInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAceptarInformacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelVentanaInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 360, 110));

        btnStaWork.setText("Status Workspace");
        btnStaWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaWorkActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 130, -1));

        btnStaInd.setText("Status Index");
        btnStaInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaIndActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaInd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 130, -1));

        btnStaLoc.setText("Status Local");
        btnStaLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaLocActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 130, -1));

        btnStaRem.setText("Status Remote");
        btnStaRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaRemActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 130, -1));

        btnInit.setText("Init");
        btnInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitActionPerformed(evt);
            }
        });
        getContentPane().add(btnInit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 119, -1));

        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        getContentPane().add(btnCommit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 119, -1));

        btnNewArchivo.setText("Nuevo Archivo");
        btnNewArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 119, -1));

        btnPull.setText("Pull");
        btnPull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPullActionPerformed(evt);
            }
        });
        getContentPane().add(btnPull, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 119, -1));

        btnPush.setText("Push");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });
        getContentPane().add(btnPush, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 119, -1));

        btnLog.setText("Log");
        getContentPane().add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, -1));

        btnZonaTrabajo.setText("Status Zona");
        getContentPane().add(btnZonaTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 130, -1));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaWorkActionPerformed

    private void btnStaLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaLocActionPerformed

    private void btnStaIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaIndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaIndActionPerformed

    private void btnStaRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaRemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaRemActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        jPanelMenuAdd.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitActionPerformed
        // TODO add your handling code here:
        jPanelMenuInit.setVisible(true);
        btnInit.setEnabled(false);
    }//GEN-LAST:event_btnInitActionPerformed

    private void btnNewArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewArchivoActionPerformed
        // TODO add your handling code here:
        jPanelMenuNewArchivo.setVisible(true);
    }//GEN-LAST:event_btnNewArchivoActionPerformed

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        // TODO add your handling code here:
        jPanelMenuCommit.setVisible(true);
    }//GEN-LAST:event_btnCommitActionPerformed

    private void btnPullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPullActionPerformed
        // TODO add your handling code here:
        jPanelVentanaInformacion.setVisible(true);
        Zona.gitPull();
        jFieldInformacionVInformacion.setText("Pull realizado Correctamente");
    }//GEN-LAST:event_btnPullActionPerformed

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        // TODO add your handling code here:
        jPanelVentanaInformacion.setVisible(true);
        Zona.gitPush();
        jFieldInformacionVInformacion.setText("Push realizado Correctamente");
    }//GEN-LAST:event_btnPushActionPerformed

    private void jbtnSeleccionarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarAddActionPerformed
        // TODO add your handling code here:
        jPanelMenuAdd.setVisible(false);
        jPanelMenuAdd2.setVisible(true);
        jTextAreaStatusWorkspaceAdd.setText(Zona.toStringWorkspace());
    }//GEN-LAST:event_jbtnSeleccionarAddActionPerformed

    private void jFieldNombreAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNombreAdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNombreAdd2ActionPerformed

    private void jFieldMensajeCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldMensajeCommitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldMensajeCommitActionPerformed

    private void jbtnAceptarCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarCommitActionPerformed
        // TODO add your handling code here:
        String nombreAutorCommit = jFieldAutorCommit.getText();
        String nombreMensajeCommit = jFieldMensajeCommit.getText();
        Zona.gitCommit(nombreAutorCommit  ,nombreMensajeCommit);
        jPanelMenuCommit.setVisible(false);
        System.out.println(Zona);
    }//GEN-LAST:event_jbtnAceptarCommitActionPerformed

    private void jFieldAutorCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldAutorCommitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldAutorCommitActionPerformed

    private void jbtnAceptarAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarAdd2ActionPerformed
        // TODO add your handling code here:
        String Archivos = jFieldNombreAdd2.getText();
        Zona.gitAdd(2,Archivos);
        jFieldNombreAdd2.setText(null);
        jTextAreaStatusWorkspaceAdd.setText(null);
        jPanelMenuAdd2.setVisible(false);
        System.out.println(Zona);
    }//GEN-LAST:event_jbtnAceptarAdd2ActionPerformed

    private void btnAceptInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptInitActionPerformed
        // TODO add your handling code here:
        String AutorInit = jFieldAutorInit.getText();
        String NombreInit = jFieldNombreInit.getText();
        
        Zona = new ZonaTrabajo(NombreInit,AutorInit);
        jPanelMenuInit.setVisible(false);
        System.out.println(Zona);
    }//GEN-LAST:event_btnAceptInitActionPerformed

    private void jFieldAutorInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldAutorInitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldAutorInitActionPerformed

    private void jFieldNombreInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNombreInitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNombreInitActionPerformed

    private void btnAceptarNewArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarNewArchivoActionPerformed
        // TODO add your handling code here:
        String nombreNew = jFieldNombreNewArchivo.getText();
        String contenidoNew = jFieldContenidoNewArchivo.getText();
        
        Zona.gitCrear(nombreNew, contenidoNew);
        
        jFieldNombreNewArchivo.setText(null);
        jFieldContenidoNewArchivo.setText(null);
        
        jPanelMenuNewArchivo.setVisible(false);
        System.out.println(Zona);
        
    }//GEN-LAST:event_btnAceptarNewArchivoActionPerformed

    private void jFieldNombreNewArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldNombreNewArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldNombreNewArchivoActionPerformed

    private void jFieldContenidoNewArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldContenidoNewArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldContenidoNewArchivoActionPerformed

    private void jbtnAgregarTodosAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarTodosAddActionPerformed
        // TODO add your handling code here:
        Zona.gitAdd(1,null);
        jPanelMenuAdd.setVisible(false);
        System.out.println(Zona);
    }//GEN-LAST:event_jbtnAgregarTodosAddActionPerformed

    private void jbtnAceptarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarInformacionActionPerformed
        // TODO add your handling code here:
        jFieldInformacionVInformacion.setText(null);
        jPanelVentanaInformacion.setVisible(false);
        System.out.println(Zona);
    }//GEN-LAST:event_jbtnAceptarInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JButton btnAceptInit;
    private javax.swing.JButton btnAceptarNewArchivo;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnInit;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnNewArchivo;
    private javax.swing.JButton btnPull;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnStaInd;
    private javax.swing.JButton btnStaLoc;
    private javax.swing.JButton btnStaRem;
    private javax.swing.JButton btnStaWork;
    private javax.swing.JButton btnZonaTrabajo;
    private javax.swing.JTextArea jAreaInformacion;
    private javax.swing.JTextField jFieldAutorCommit;
    public static javax.swing.JTextField jFieldAutorInit;
    private javax.swing.JTextField jFieldContenidoNewArchivo;
    private javax.swing.JTextField jFieldInformacionVInformacion;
    private javax.swing.JTextField jFieldMensajeCommit;
    private javax.swing.JTextField jFieldNombreAdd2;
    public static javax.swing.JTextField jFieldNombreInit;
    private javax.swing.JTextField jFieldNombreNewArchivo;
    private javax.swing.JTextField jFieldTituloPanelStatus;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelMenuAdd;
    private javax.swing.JPanel jPanelMenuAdd2;
    private javax.swing.JPanel jPanelMenuCommit;
    private javax.swing.JPanel jPanelMenuInit;
    private javax.swing.JPanel jPanelMenuNewArchivo;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JPanel jPanelVentanaInformacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaStatusWorkspaceAdd;
    private javax.swing.JButton jbtnAceptarAdd2;
    private javax.swing.JButton jbtnAceptarCommit;
    private javax.swing.JButton jbtnAceptarInformacion;
    private javax.swing.JButton jbtnAceptarPanelStatus;
    private javax.swing.JButton jbtnAgregarTodosAdd;
    private javax.swing.JButton jbtnSeleccionarAdd;
    // End of variables declaration//GEN-END:variables
}
