/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import Modelo.ZonaTrabajo;

/**
 *
 * @author Hernan
 */
public class InterfazGit extends javax.swing.JFrame {
    
    private ZonaTrabajo Zona;
    
    /**
     * Creates new form InterfazGit
     */
    public InterfazGit() {
        initComponents();
        // Se centra JFrame
        this.setLocationRelativeTo(null);
        
        // Se ocultan los Jpanel debido a que no se ocupan en este momento
        jPanelMenuAdd.setVisible(false);
        jPanelMenuAdd2.setVisible(false);
        jPanelMenuAdd2.setVisible(false);
        jPanelMenuInit.setVisible(false);
        jPanelMenuNewArchivo.setVisible(false);
        jPanelStatus.setVisible(false);
        jPanelMenuCommit.setVisible(false);   
        jPanelVentanaInformacion.setVisible(false);
        
        // Lo siguiente se realiza para que obligatoriamente se realice un inicio de repositorio para
        // poder ocupar los botones Git
        btnNewArchivo.setEnabled(false);
        btnAdd.setEnabled(false);
        btnCommit.setEnabled(false);
        btnPush.setEnabled(false);
        btnPull.setEnabled(false);
        btnStaWork.setEnabled(false);
        btnStaInd.setEnabled(false);
        btnStaLoc.setEnabled(false);
        btnStaRem.setEnabled(false);
        btnLog.setEnabled(false);
        btnZonaTrabajo.setEnabled(false);
    }
    
    /**
     * Tiene el objetivo de bloquear los botones de JFrame, debido a que al estar utilizando
     * los JPanel un click puede verse traspapelado y terminar usando botondes del JFrame.
     */
    public void BloqBotones(){
        btnInit.setEnabled(false);
        btnNewArchivo.setEnabled(false);
        btnAdd.setEnabled(false);
        btnCommit.setEnabled(false);
        btnPush.setEnabled(false);
        btnPull.setEnabled(false);
        btnStaWork.setEnabled(false);
        btnStaInd.setEnabled(false);
        btnStaLoc.setEnabled(false);
        btnStaRem.setEnabled(false);
        btnLog.setEnabled(false);
        btnZonaTrabajo.setEnabled(false);
    }
    
    /**
     * Libera los botones al terminar de usar JPanels.
     */
    public void DesBotones(){
        btnInit.setEnabled(true);
        btnNewArchivo.setEnabled(true);
        btnAdd.setEnabled(true);
        btnCommit.setEnabled(true);
        btnPush.setEnabled(true);
        btnPull.setEnabled(true);
        btnStaWork.setEnabled(true);
        btnStaInd.setEnabled(true);
        btnStaLoc.setEnabled(true);
        btnStaRem.setEnabled(true);
        btnLog.setEnabled(true);
        btnZonaTrabajo.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentanaInformacion = new javax.swing.JPanel();
        jFieldInformacionVInformacion = new javax.swing.JTextField();
        jbtnAceptarInformacion = new javax.swing.JButton();
        jLabelInformacionPanelVInformacion = new javax.swing.JLabel();
        jPanelStatus = new javax.swing.JPanel();
        jFieldTituloPanelStatus = new javax.swing.JTextField();
        jAreaPanelStatus = new javax.swing.JScrollPane();
        jTextAreaInformacionPanelStatus = new javax.swing.JTextArea();
        jbtnAceptarPanelStatus = new javax.swing.JButton();
        jPanelMenuCommit = new javax.swing.JPanel();
        jFieldAutorCommit = new javax.swing.JTextField();
        jFieldMensajeCommit = new javax.swing.JTextField();
        jLabelAutorMenuCommit = new javax.swing.JLabel();
        jLabelMensajeMenuCommit = new javax.swing.JLabel();
        jbtnAceptarCommit = new javax.swing.JButton();
        jLabelTituloMenuCommit = new javax.swing.JLabel();
        jPanelMenuAdd2 = new javax.swing.JPanel();
        jLabelNombreArchivosMenuAdd = new javax.swing.JLabel();
        jFieldNombreAdd2 = new javax.swing.JTextField();
        jLabelTituloMenuAdd2 = new javax.swing.JLabel();
        jbtnAceptarAdd2 = new javax.swing.JButton();
        jLabelFormatoArchivosMenuAdd = new javax.swing.JLabel();
        jLabelWorkspaceMenuAdd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStatusWorkspaceAdd = new javax.swing.JTextArea();
        jPanelMenuAdd = new javax.swing.JPanel();
        jLabelTituloMenuAdd = new javax.swing.JLabel();
        jbtnAgregarTodosAdd = new javax.swing.JButton();
        jbtnSeleccionarAdd = new javax.swing.JButton();
        jPanelMenuInit = new javax.swing.JPanel();
        jLabelAutorMenuInit = new javax.swing.JLabel();
        jLabelNombreRepoMenuInit = new javax.swing.JLabel();
        btnAceptInit = new javax.swing.JButton();
        jLabelTituloMenuInit = new javax.swing.JLabel();
        jFieldAutorInit = new javax.swing.JTextField();
        jFieldNombreInit = new javax.swing.JTextField();
        jPanelMenuNewArchivo = new javax.swing.JPanel();
        jLabelContenidoMenuNewArchivo = new javax.swing.JLabel();
        btnAceptarNewArchivo = new javax.swing.JButton();
        jLabelTituloMenuNewArchivo = new javax.swing.JLabel();
        jFieldNombreNewArchivo = new javax.swing.JTextField();
        jFieldContenidoNewArchivo = new javax.swing.JTextField();
        jLabelNombreMenuNewArchivo = new javax.swing.JLabel();
        btnStaWork = new javax.swing.JButton();
        btnStaInd = new javax.swing.JButton();
        btnStaLoc = new javax.swing.JButton();
        btnStaRem = new javax.swing.JButton();
        btnInit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCommit = new javax.swing.JButton();
        btnNewArchivo = new javax.swing.JButton();
        btnPull = new javax.swing.JButton();
        btnPush = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnZonaTrabajo = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(526, 460));
        setMinimumSize(new java.awt.Dimension(526, 460));
        setPreferredSize(new java.awt.Dimension(526, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelVentanaInformacion.setMaximumSize(new java.awt.Dimension(360, 121));
        jPanelVentanaInformacion.setMinimumSize(new java.awt.Dimension(360, 121));

        jFieldInformacionVInformacion.setEditable(false);

        jbtnAceptarInformacion.setText("Aceptar");
        jbtnAceptarInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarInformacionActionPerformed(evt);
            }
        });

        jLabelInformacionPanelVInformacion.setText("Informacion");

        javax.swing.GroupLayout jPanelVentanaInformacionLayout = new javax.swing.GroupLayout(jPanelVentanaInformacion);
        jPanelVentanaInformacion.setLayout(jPanelVentanaInformacionLayout);
        jPanelVentanaInformacionLayout.setHorizontalGroup(
            jPanelVentanaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                .addGroup(jPanelVentanaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jFieldInformacionVInformacion))
                    .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jbtnAceptarInformacion)
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentanaInformacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelInformacionPanelVInformacion)
                .addGap(145, 145, 145))
        );
        jPanelVentanaInformacionLayout.setVerticalGroup(
            jPanelVentanaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInformacionPanelVInformacion)
                .addGap(24, 24, 24)
                .addComponent(jFieldInformacionVInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAceptarInformacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelVentanaInformacion);
        jPanelVentanaInformacion.setBounds(90, 150, 360, 121);

        jPanelStatus.setMaximumSize(new java.awt.Dimension(526, 460));
        jPanelStatus.setPreferredSize(new java.awt.Dimension(526, 460));
        jPanelStatus.setRequestFocusEnabled(false);

        jFieldTituloPanelStatus.setEditable(false);

        jTextAreaInformacionPanelStatus.setEditable(false);
        jTextAreaInformacionPanelStatus.setColumns(20);
        jTextAreaInformacionPanelStatus.setRows(5);
        jAreaPanelStatus.setViewportView(jTextAreaInformacionPanelStatus);

        jbtnAceptarPanelStatus.setText("Aceptar");
        jbtnAceptarPanelStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarPanelStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStatusLayout = new javax.swing.GroupLayout(jPanelStatus);
        jPanelStatus.setLayout(jPanelStatusLayout);
        jPanelStatusLayout.setHorizontalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStatusLayout.createSequentialGroup()
                        .addComponent(jAreaPanelStatus)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusLayout.createSequentialGroup()
                        .addGap(0, 174, Short.MAX_VALUE)
                        .addGroup(jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusLayout.createSequentialGroup()
                                .addComponent(jbtnAceptarPanelStatus)
                                .addGap(204, 204, 204))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStatusLayout.createSequentialGroup()
                                .addComponent(jFieldTituloPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179))))))
        );
        jPanelStatusLayout.setVerticalGroup(
            jPanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatusLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jFieldTituloPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAreaPanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAceptarPanelStatus)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelStatus);
        jPanelStatus.setBounds(10, 10, 500, 400);

        jPanelMenuCommit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelAutorMenuCommit.setText("Ingrese Autor Commit:");

        jLabelMensajeMenuCommit.setText("Ingrese Mensaje Descriptivo:");

        jbtnAceptarCommit.setText("Aceptar");
        jbtnAceptarCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarCommitActionPerformed(evt);
            }
        });

        jLabelTituloMenuCommit.setText("Menu Commit");

        javax.swing.GroupLayout jPanelMenuCommitLayout = new javax.swing.GroupLayout(jPanelMenuCommit);
        jPanelMenuCommit.setLayout(jPanelMenuCommitLayout);
        jPanelMenuCommitLayout.setHorizontalGroup(
            jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCommitLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAutorMenuCommit)
                    .addComponent(jLabelMensajeMenuCommit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFieldAutorCommit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldMensajeCommit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuCommitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuCommitLayout.createSequentialGroup()
                        .addComponent(jLabelTituloMenuCommit)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuCommitLayout.createSequentialGroup()
                        .addComponent(jbtnAceptarCommit)
                        .addGap(132, 132, 132))))
        );
        jPanelMenuCommitLayout.setVerticalGroup(
            jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuCommitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloMenuCommit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutorMenuCommit)
                    .addComponent(jFieldAutorCommit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMenuCommitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldMensajeCommit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMensajeMenuCommit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAceptarCommit)
                .addContainerGap())
        );

        getContentPane().add(jPanelMenuCommit);
        jPanelMenuCommit.setBounds(90, 160, 340, 140);

        jPanelMenuAdd2.setMaximumSize(new java.awt.Dimension(500, 410));
        jPanelMenuAdd2.setMinimumSize(new java.awt.Dimension(500, 420));
        jPanelMenuAdd2.setPreferredSize(new java.awt.Dimension(500, 410));

        jLabelNombreArchivosMenuAdd.setText("Ingrese Nombres de Archivos: ");

        jLabelTituloMenuAdd2.setText("Menu Add");

        jbtnAceptarAdd2.setText("Aceptar");
        jbtnAceptarAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceptarAdd2ActionPerformed(evt);
            }
        });

        jLabelFormatoArchivosMenuAdd.setText("Formato de Ingreso: NombreArchivo NombreArchivo NombreArchivo");

        jLabelWorkspaceMenuAdd.setText("Workspace");

        jTextAreaStatusWorkspaceAdd.setEditable(false);
        jTextAreaStatusWorkspaceAdd.setColumns(20);
        jTextAreaStatusWorkspaceAdd.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextAreaStatusWorkspaceAdd.setRows(5);
        jScrollPane1.setViewportView(jTextAreaStatusWorkspaceAdd);

        javax.swing.GroupLayout jPanelMenuAdd2Layout = new javax.swing.GroupLayout(jPanelMenuAdd2);
        jPanelMenuAdd2.setLayout(jPanelMenuAdd2Layout);
        jPanelMenuAdd2Layout.setHorizontalGroup(
            jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                .addGroup(jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNombreArchivosMenuAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jFieldNombreAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFormatoArchivosMenuAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabelTituloMenuAdd2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                .addGroup(jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jbtnAceptarAdd2))
                    .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabelWorkspaceMenuAdd)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMenuAdd2Layout.setVerticalGroup(
            jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAdd2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloMenuAdd2)
                .addGap(18, 18, 18)
                .addComponent(jLabelFormatoArchivosMenuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelMenuAdd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreArchivosMenuAdd)
                    .addComponent(jFieldNombreAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelWorkspaceMenuAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAceptarAdd2)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenuAdd2);
        jPanelMenuAdd2.setBounds(10, 10, 500, 410);

        jPanelMenuAdd.setMaximumSize(new java.awt.Dimension(214, 128));

        jLabelTituloMenuAdd.setText("Menu Add");

        jbtnAgregarTodosAdd.setText("Agregar todos los archivos");
        jbtnAgregarTodosAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarTodosAddActionPerformed(evt);
            }
        });

        jbtnSeleccionarAdd.setText("Selecionar archivos a agregar");
        jbtnSeleccionarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuAddLayout = new javax.swing.GroupLayout(jPanelMenuAdd);
        jPanelMenuAdd.setLayout(jPanelMenuAddLayout);
        jPanelMenuAddLayout.setHorizontalGroup(
            jPanelMenuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAddLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanelMenuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuAddLayout.createSequentialGroup()
                        .addGroup(jPanelMenuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnSeleccionarAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnAgregarTodosAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuAddLayout.createSequentialGroup()
                        .addComponent(jLabelTituloMenuAdd)
                        .addGap(78, 78, 78))))
        );
        jPanelMenuAddLayout.setVerticalGroup(
            jPanelMenuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloMenuAdd)
                .addGap(18, 18, 18)
                .addComponent(jbtnAgregarTodosAdd)
                .addGap(18, 18, 18)
                .addComponent(jbtnSeleccionarAdd)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenuAdd);
        jPanelMenuAdd.setBounds(160, 150, 214, 128);

        jPanelMenuInit.setMaximumSize(new java.awt.Dimension(360, 156));
        jPanelMenuInit.setMinimumSize(new java.awt.Dimension(360, 156));
        jPanelMenuInit.setPreferredSize(new java.awt.Dimension(360, 156));

        jLabelAutorMenuInit.setText("Ingrese Nombre Autor:");

        jLabelNombreRepoMenuInit.setText("Ingrese Nombre Repositorio:");

        btnAceptInit.setText("Aceptar");
        btnAceptInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptInitActionPerformed(evt);
            }
        });

        jLabelTituloMenuInit.setText("Menu Init");

        javax.swing.GroupLayout jPanelMenuInitLayout = new javax.swing.GroupLayout(jPanelMenuInit);
        jPanelMenuInit.setLayout(jPanelMenuInitLayout);
        jPanelMenuInitLayout.setHorizontalGroup(
            jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuInitLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAutorMenuInit)
                    .addComponent(jLabelNombreRepoMenuInit))
                .addGap(24, 24, 24)
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFieldAutorInit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldNombreInit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuInitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuInitLayout.createSequentialGroup()
                        .addComponent(jLabelTituloMenuInit)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuInitLayout.createSequentialGroup()
                        .addComponent(btnAceptInit)
                        .addGap(133, 133, 133))))
        );
        jPanelMenuInitLayout.setVerticalGroup(
            jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuInitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloMenuInit)
                .addGap(16, 16, 16)
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutorMenuInit)
                    .addComponent(jFieldAutorInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuInitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreRepoMenuInit)
                    .addComponent(jFieldNombreInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptInit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenuInit);
        jPanelMenuInit.setBounds(90, 150, 360, 156);

        jLabelContenidoMenuNewArchivo.setText("Ingrese Contenido Archivo:");

        btnAceptarNewArchivo.setText("Aceptar");
        btnAceptarNewArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarNewArchivoActionPerformed(evt);
            }
        });

        jLabelTituloMenuNewArchivo.setText("Menu Nuevo Archivo");

        jLabelNombreMenuNewArchivo.setText("Ingrese Nombre Archivo:");

        javax.swing.GroupLayout jPanelMenuNewArchivoLayout = new javax.swing.GroupLayout(jPanelMenuNewArchivo);
        jPanelMenuNewArchivo.setLayout(jPanelMenuNewArchivoLayout);
        jPanelMenuNewArchivoLayout.setHorizontalGroup(
            jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuNewArchivoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreMenuNewArchivo)
                    .addComponent(jLabelContenidoMenuNewArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFieldNombreNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFieldContenidoNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuNewArchivoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuNewArchivoLayout.createSequentialGroup()
                        .addComponent(jLabelTituloMenuNewArchivo)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuNewArchivoLayout.createSequentialGroup()
                        .addComponent(btnAceptarNewArchivo)
                        .addGap(132, 132, 132))))
        );
        jPanelMenuNewArchivoLayout.setVerticalGroup(
            jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuNewArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloMenuNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreMenuNewArchivo)
                    .addComponent(jFieldNombreNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMenuNewArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContenidoMenuNewArchivo)
                    .addComponent(jFieldContenidoNewArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptarNewArchivo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelMenuNewArchivo);
        jPanelMenuNewArchivo.setBounds(90, 150, 340, 160);

        btnStaWork.setText("Status Workspace");
        btnStaWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaWorkActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaWork);
        btnStaWork.setBounds(340, 120, 130, 23);

        btnStaInd.setText("Status Index");
        btnStaInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaIndActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaInd);
        btnStaInd.setBounds(340, 160, 130, 23);

        btnStaLoc.setText("Status Local");
        btnStaLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaLocActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaLoc);
        btnStaLoc.setBounds(340, 200, 130, 23);

        btnStaRem.setText("Status Remote");
        btnStaRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaRemActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaRem);
        btnStaRem.setBounds(340, 240, 130, 23);

        btnInit.setText("Init");
        btnInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitActionPerformed(evt);
            }
        });
        getContentPane().add(btnInit);
        btnInit.setBounds(70, 120, 120, 23);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(70, 200, 119, 23);

        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });
        getContentPane().add(btnCommit);
        btnCommit.setBounds(70, 240, 119, 23);

        btnNewArchivo.setText("Nuevo Archivo");
        btnNewArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewArchivo);
        btnNewArchivo.setBounds(70, 160, 119, 23);

        btnPull.setText("Pull");
        btnPull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPullActionPerformed(evt);
            }
        });
        getContentPane().add(btnPull);
        btnPull.setBounds(70, 320, 119, 23);

        btnPush.setText("Push");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });
        getContentPane().add(btnPush);
        btnPush.setBounds(70, 280, 119, 23);

        btnLog.setText("Log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        getContentPane().add(btnLog);
        btnLog.setBounds(340, 280, 130, 23);

        btnZonaTrabajo.setText("Status Zona");
        btnZonaTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZonaTrabajoActionPerformed(evt);
            }
        });
        getContentPane().add(btnZonaTrabajo);
        btnZonaTrabajo.setBounds(340, 320, 130, 23);

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(LabelFondo);
        LabelFondo.setBounds(0, 0, 530, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Boton Status Workspace
     * @param evt Evento
     */
    private void btnStaWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaWorkActionPerformed
        // TODO add your handling code here:
        jPanelStatus.setVisible(true);
        BloqBotones();
        jFieldTituloPanelStatus.setText("Workspace");
        jTextAreaInformacionPanelStatus.setText(Zona.toStringWorkspace());
    }//GEN-LAST:event_btnStaWorkActionPerformed
    
    /**
     * Boton Status Local Repository
     * @param evt Evento
     */
    private void btnStaLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaLocActionPerformed
        // TODO add your handling code here:
        jPanelStatus.setVisible(true);
        BloqBotones();
        jFieldTituloPanelStatus.setText("Local Repository");
        jTextAreaInformacionPanelStatus.setText(Zona.toStringLocal());
    }//GEN-LAST:event_btnStaLocActionPerformed
    
    /**
     * Boton Status Index
     * @param evt Evento
     */
    private void btnStaIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaIndActionPerformed
        // TODO add your handling code here:
        jPanelStatus.setVisible(true);
        BloqBotones();
        jFieldTituloPanelStatus.setText("Index");
        jTextAreaInformacionPanelStatus.setText(Zona.toStringIndex());
    }//GEN-LAST:event_btnStaIndActionPerformed
    
    /**
     * Boton Status Remote Repository
     * @param evt Evento
     */
    private void btnStaRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaRemActionPerformed
        // TODO add your handling code here:
        jPanelStatus.setVisible(true);
        BloqBotones();
        jFieldTituloPanelStatus.setText("Remote Repositoy");
        jTextAreaInformacionPanelStatus.setText(Zona.toStringRemote());
    }//GEN-LAST:event_btnStaRemActionPerformed
    
    /**
     * Boton Add de JFrame
     * @param evt Evento
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(Zona.verificarWorkspace()){
            jPanelMenuAdd.setVisible(true);
            BloqBotones();
        }else{
            jPanelVentanaInformacion.setVisible(true);
            BloqBotones();
            jFieldInformacionVInformacion.setText("No hay archivos en Workspace");
        }       
    }//GEN-LAST:event_btnAddActionPerformed
    
    /**
     * Boton Init de JFrame
     * @param evt Evento
     */
    private void btnInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitActionPerformed
        // TODO add your handling code here:
        jPanelMenuInit.setVisible(true);
        BloqBotones();
        btnInit.setEnabled(false);
        
    }//GEN-LAST:event_btnInitActionPerformed
    
    /**
     * Boton Nuevo Archivo de JFrame
     * @param evt Evento
     */
    private void btnNewArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewArchivoActionPerformed
        // TODO add your handling code here:
        jPanelMenuNewArchivo.setVisible(true);
        BloqBotones();
    }//GEN-LAST:event_btnNewArchivoActionPerformed
    
    /**
     * Boton Commit de JFrame
     * @param evt Evento
     */
    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        // TODO add your handling code here:
        if(Zona.verificarIndex()){
            jPanelMenuCommit.setVisible(true);
            BloqBotones();
        }else{
            jPanelVentanaInformacion.setVisible(true); 
            BloqBotones();
            jFieldInformacionVInformacion.setText("No hay archivos en Index");
        }
    }//GEN-LAST:event_btnCommitActionPerformed
    
    /**
     * Boton Pull de JFrame
     * @param evt Evento
     */
    private void btnPullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPullActionPerformed
        // TODO add your handling code here:
        if(Zona.verificarRemote()){
            jPanelVentanaInformacion.setVisible(true);
            BloqBotones();
            Zona.gitPull();
            jFieldInformacionVInformacion.setText("Pull Realizado Correctamente");
        }else{
            jPanelVentanaInformacion.setVisible(true); 
            BloqBotones();
            jFieldInformacionVInformacion.setText("No hay Commits en Remote Repository");
        }
    }//GEN-LAST:event_btnPullActionPerformed
    
    /**
     * Boton Push de JFrame
     * @param evt Evento
     */
    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        // TODO add your handling code here:
        if(Zona.verificarLocal()){
            jPanelVentanaInformacion.setVisible(true);
            BloqBotones();
            Zona.gitPush();
            jFieldInformacionVInformacion.setText("Push Realizado Correctamente");
        }else{
            jPanelVentanaInformacion.setVisible(true);
            BloqBotones();
            jFieldInformacionVInformacion.setText("No hay Commits en Local Repository");
        }
    }//GEN-LAST:event_btnPushActionPerformed
    
    /**
     * Boton Seleccionar Archivos de JPanelMenuAdd
     * @param evt Evento
     */
    private void jbtnSeleccionarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarAddActionPerformed
        // TODO add your handling code here:
        jPanelMenuAdd.setVisible(false);
        jPanelMenuAdd2.setVisible(true);
        jTextAreaStatusWorkspaceAdd.setText(Zona.toStringWorkspace());
    }//GEN-LAST:event_jbtnSeleccionarAddActionPerformed
    
    /**
     * Boton Aceptar de JPanelMenuCommit
     * @param evt Evento
     */
    private void jbtnAceptarCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarCommitActionPerformed
        // TODO add your handling code here:
        String nombreAutorCommit = jFieldAutorCommit.getText();
        String nombreMensajeCommit = jFieldMensajeCommit.getText();
        Zona.gitCommit(nombreAutorCommit  ,nombreMensajeCommit);
        jPanelMenuCommit.setVisible(false);
        jFieldAutorCommit.setText(null);
        jFieldMensajeCommit.setText(null);
        jPanelVentanaInformacion.setVisible(true);
        jFieldInformacionVInformacion.setText("Commit Realizado Correctamente");
    }//GEN-LAST:event_jbtnAceptarCommitActionPerformed
    
    /**
     * Boton Aceptar de JPanelMenuAdd2
     * @param evt Evento
     */
    private void jbtnAceptarAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarAdd2ActionPerformed
        // TODO add your handling code here:
        String Archivos = jFieldNombreAdd2.getText();
        Zona.gitAdd(2,Archivos);
        jFieldNombreAdd2.setText(null);
        jTextAreaStatusWorkspaceAdd.setText(null);
        jPanelMenuAdd2.setVisible(false);
        jPanelVentanaInformacion.setVisible(true);
        jFieldInformacionVInformacion.setText("Add Realizado Correctamente");
    }//GEN-LAST:event_jbtnAceptarAdd2ActionPerformed
    
    /**
     * Boton Aceptar de JPanelMenuInit
     * @param evt Evento
     */
    private void btnAceptInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptInitActionPerformed
        // TODO add your handling code here:
        String AutorInit = jFieldAutorInit.getText();
        String NombreInit = jFieldNombreInit.getText();
        
        Zona = new ZonaTrabajo(NombreInit,AutorInit);
        jFieldAutorInit.setText(null);
        jFieldNombreInit.setText(null);
        jPanelMenuInit.setVisible(false);
        jPanelVentanaInformacion.setVisible(true);
        jFieldInformacionVInformacion.setText("Init Realizado Correctamente");
    }//GEN-LAST:event_btnAceptInitActionPerformed
    
    /**
     * Boton Aceptar de JPanelMenuNewArchivo
     * @param evt Evento
     */
    private void btnAceptarNewArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarNewArchivoActionPerformed
        // TODO add your handling code here:
        String nombreNew = jFieldNombreNewArchivo.getText();
        String contenidoNew = jFieldContenidoNewArchivo.getText();
        
        Zona.gitCrear(nombreNew, contenidoNew);
        
        jFieldNombreNewArchivo.setText(null);
        jFieldContenidoNewArchivo.setText(null);
        
        jPanelMenuNewArchivo.setVisible(false);
        jPanelVentanaInformacion.setVisible(true);
        jFieldInformacionVInformacion.setText("Nuevo Archivo Realizado Correctamente");
        
    }//GEN-LAST:event_btnAceptarNewArchivoActionPerformed
    
    /**
     * Boton Agregar todos los archivos de JPanelMenuAdd
     * @param evt Evento
     */
    private void jbtnAgregarTodosAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarTodosAddActionPerformed
        // TODO add your handling code here:
        Zona.gitAdd(1,null);
        jPanelMenuAdd.setVisible(false);
        jPanelVentanaInformacion.setVisible(true);
        jFieldInformacionVInformacion.setText("Add Realizado Correctamente");
    }//GEN-LAST:event_jbtnAgregarTodosAddActionPerformed
    
    /**
     * Boton Acpetar de JPanelVentanaInformacion
     * @param evt Evento
     */
    private void jbtnAceptarInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarInformacionActionPerformed
        // TODO add your handling code here:
        jFieldInformacionVInformacion.setText(null);
        jPanelVentanaInformacion.setVisible(false);
        DesBotones();
    }//GEN-LAST:event_jbtnAceptarInformacionActionPerformed
    
    /**
     * Boton Aceptar de jPanelStatus
     * @param evt Evento
     */
    private void jbtnAceptarPanelStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceptarPanelStatusActionPerformed
        // TODO add your handling code here:
        jPanelStatus.setVisible(false);
        jTextAreaInformacionPanelStatus.setText(null);
        DesBotones();
    }//GEN-LAST:event_jbtnAceptarPanelStatusActionPerformed
    
    /**
     * Boton Log de JFrame
     * @param evt Evento
     */
    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        jPanelStatus.setVisible(true);
        BloqBotones();
        jFieldTituloPanelStatus.setText("Log");
        jTextAreaInformacionPanelStatus.setText(Zona.gitLog());
    }//GEN-LAST:event_btnLogActionPerformed
    
    /**
     * Boton Zona Trabajo de JFrame
     * @param evt Evento
     */
    private void btnZonaTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZonaTrabajoActionPerformed
        // TODO add your handling code here:
        jPanelStatus.setVisible(true);
        BloqBotones();
        jFieldTituloPanelStatus.setText("Zona de Trabajo");
        jTextAreaInformacionPanelStatus.setText(Zona.toString());
             
    }//GEN-LAST:event_btnZonaTrabajoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JButton btnAceptInit;
    private javax.swing.JButton btnAceptarNewArchivo;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCommit;
    private javax.swing.JButton btnInit;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnNewArchivo;
    private javax.swing.JButton btnPull;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnStaInd;
    private javax.swing.JButton btnStaLoc;
    private javax.swing.JButton btnStaRem;
    private javax.swing.JButton btnStaWork;
    private javax.swing.JButton btnZonaTrabajo;
    private javax.swing.JScrollPane jAreaPanelStatus;
    private javax.swing.JTextField jFieldAutorCommit;
    public static javax.swing.JTextField jFieldAutorInit;
    private javax.swing.JTextField jFieldContenidoNewArchivo;
    private javax.swing.JTextField jFieldInformacionVInformacion;
    private javax.swing.JTextField jFieldMensajeCommit;
    private javax.swing.JTextField jFieldNombreAdd2;
    public static javax.swing.JTextField jFieldNombreInit;
    private javax.swing.JTextField jFieldNombreNewArchivo;
    private javax.swing.JTextField jFieldTituloPanelStatus;
    private javax.swing.JLabel jLabelAutorMenuCommit;
    private javax.swing.JLabel jLabelAutorMenuInit;
    private javax.swing.JLabel jLabelContenidoMenuNewArchivo;
    private javax.swing.JLabel jLabelFormatoArchivosMenuAdd;
    private javax.swing.JLabel jLabelInformacionPanelVInformacion;
    private javax.swing.JLabel jLabelMensajeMenuCommit;
    private javax.swing.JLabel jLabelNombreArchivosMenuAdd;
    private javax.swing.JLabel jLabelNombreMenuNewArchivo;
    private javax.swing.JLabel jLabelNombreRepoMenuInit;
    private javax.swing.JLabel jLabelTituloMenuAdd;
    private javax.swing.JLabel jLabelTituloMenuAdd2;
    private javax.swing.JLabel jLabelTituloMenuCommit;
    private javax.swing.JLabel jLabelTituloMenuInit;
    private javax.swing.JLabel jLabelTituloMenuNewArchivo;
    private javax.swing.JLabel jLabelWorkspaceMenuAdd;
    private javax.swing.JPanel jPanelMenuAdd;
    private javax.swing.JPanel jPanelMenuAdd2;
    private javax.swing.JPanel jPanelMenuCommit;
    private javax.swing.JPanel jPanelMenuInit;
    private javax.swing.JPanel jPanelMenuNewArchivo;
    private javax.swing.JPanel jPanelStatus;
    private javax.swing.JPanel jPanelVentanaInformacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaInformacionPanelStatus;
    private javax.swing.JTextArea jTextAreaStatusWorkspaceAdd;
    private javax.swing.JButton jbtnAceptarAdd2;
    private javax.swing.JButton jbtnAceptarCommit;
    private javax.swing.JButton jbtnAceptarInformacion;
    private javax.swing.JButton jbtnAceptarPanelStatus;
    private javax.swing.JButton jbtnAgregarTodosAdd;
    private javax.swing.JButton jbtnSeleccionarAdd;
    // End of variables declaration//GEN-END:variables
}
